### ISSUE TITLE
Line comments not always supported?

### ISSUE THREAD

**Issue by samoht** [avsm/ocaml-yaml#72]
In some cases, comments are breaking the parser. Seems that:

```yaml
foo:
  - bar: |
#    a comment
      xxx
```

Is not supported properly. (and the parse error is reported wrongly, as in #36)
